/**
 * Word lists for coding–decoding. Plain everyday English (British spelling), banking and daily-life flavour.
 */

const words = (s: string) =>
  s
    .split(/\s+/)
    .map((w) => w.trim())
    .filter(Boolean);

/** Words for letter / number coding (4–8 letters). */
export const CODE_WORDS: readonly string[] = words(`
  BANK LOAN CASH GOLD MONEY PRICE TRADE STOCK SHARE BOND FUND CREDIT DEBIT RUPEE COIN NOTE MARKET CLERK BRANCH
  PROFIT SALES VALUE RATE INCOME SAVING BUDGET CHEQUE LEDGER BALANCE ACCOUNT DEPOSIT INTEREST
  APPLE MANGO GRAPE LEMON PLANT FLOWER GARDEN RIVER OCEAN CLOUD STORM WATER EARTH PLANET TRAIN TRUCK CYCLE
  SCHOOL PENCIL MARKER PAPER CHAIR TABLE WINDOW HOUSE CANDLE LAMP LIGHT NIGHT MORNING SUMMER WINTER MONSOON
  FARMER TRACTOR WHEAT SUGAR SPICE COFFEE BREAD BUTTER CHEESE PEACOCK TIGER HORSE CAMEL MONKEY PARROT
  DOCTOR NURSE PILOT TAILOR PAINTER SINGER DANCER WRITER PLAYER CRICKET HOCKEY TENNIS FOOTBALL
  MOBILE LAPTOP CAMERA SCREEN BUTTON POCKET JACKET SHIRT GLOVE WATCH CLOCK RADIO PHONE MOUSE
  BRIDGE TEMPLE CASTLE PALACE MUSEUM LIBRARY STATION AIRPORT HARBOUR VILLAGE CITY NATION WORLD
  SILVER COPPER IRON STEEL MARBLE STONE BRICK CEMENT TIMBER GLASS PLASTIC RUBBER COTTON SILK WOOL
  FRIEND FATHER MOTHER SISTER BROTHER UNCLE COUSIN FAMILY PEOPLE LEADER MEMBER
  DREAM SMILE HAPPY BRAVE QUICK SMART BRIGHT STRONG GENTLE PROUD CLEAN FRESH SWEET
`);

/** Candidate words for "how many letters stay in place" (distinct letters are enforced at load). */
const IN_PLACE_RAW = words(`
  PLANT BREAD CHAIR TABLE LIGHT NIGHT MONEY HOUSE WATER EARTH OCEAN SUGAR SPICE BRICK CLOUD STORM TRAIN TRUCK
  PAINT STONE FIGHT PRICE TRADE STOCK SHARE BLAME CRANE FLAME GRAPE LEMON MANGO PEACH MELON OLIVE TIGER HORSE
  ZEBRA CAMEL SNAKE SHIRT SKIRT SCARF GLOVE WATCH RADIO PHONE MOUSE CANDY BAKER CLERK TOWEL PLATE KNIFE BRUSH
  DRINK FRUIT JUICE MOVIE MUSIC DANCE SPORT WORLD EMPTY FIRST GHOST BELOW DIRTY CHIMP BEFIT ADEPT AGLOW CHOPS
  BIRTH FORTY DOUBT BLUNT GUEST PLUMB CRISP FROST BLOCK STAMP CAMPS QUICK JUMPS BOXER FAIRY HONEY SLICE CRUMB
  BLINK BRAVE CRAFT DWARF FLASK GRIND HUMAN LUNCH NORTH SOUTH ALOFT ABHOR BEGIN BELTS CHINS DEFT GLORY FILMS
  ANGRY BLOWS CHEST DENTS FLING GIRTH HOIST KNOTS MOIST NOBLE PROUD QUART ROUGH STEAM THING VOICE WRIST YOUTH
  PLANET GARDEN FLOWER MARKET BRANCH CREDIT PROFIT SILVER NICKEL WINTER SPRING FORMAT CHAPEL CASTLE TEMPLE
  BRIDGE FAMOUS FIGURE STREAM SQUARE OBJECT NUMBER PENCIL MARKER CANDLE JACKET POCKET ROCKET TICKET BASKET
  BUCKET CAMERA GUITAR VIOLIN FATHER MOTHER FRIEND PARENT DRAGON MONKEY DONKEY TURKEY PIRATE SAILOR PLAYER
  SINGER DANCER WRITER ALMOST BIOPSY CHINTZ BEGINS HONEST MODEST GOLDEN SPIDER FOREST SALMON SHRIMP PRAWNS
  ORANGE CLIENT AGENCY BRANDS GROUND PUBLIC POLICY SYMBOL BORING CHARMS DEPTHS FLIGHT GLOBAL HUNTER IMPORT
  JUMPER KIDNEY LIQUID MOBILE NAPKIN OXYGEN PLURAL RESCUE SOCKET THRONE UNSAID VORTEX WANDER YOGURT
  MONARCH BLISTER CHAPTER PLASTIC DOLPHIN KITCHEN PICTURE FARMING BANKING COUNTRY VICTORY HISTORY FACTORY
  SOLDIER ANCHORS CLIMATE COMPLEX DYNAMIC EXPLAIN FORTUNE GRAVITY JOURNEY MACHINE ORCHIDS PACKING RAINBOW
  UNIFORM WALNUTS WORSHIP MUSTARD PLANETS BLANKET CUSHION TRUMPET BROTHER FIGHTER PAINTER PRINTED MINDSET
  HOSPITAL ABSOLUTE BLACKOUT CHARMING COMPUTER DAUGHTER FLOURISH GRAPHICS HANDSOME MOISTURE PORTABLE QUESTION
  SHOULDER SPECTRUM TRIANGLE WATCHDOG BIRTHDAY CUSTOMER KEYBOARD PLATFORM REPUBLIC SANDWICH THURSDAY
  EDUCATION GUNPOWDER COPYRIGHT HYDRAULIC CLOTHING DOCUMENT BACKFIRE BOUNDARY HUMANITY JOYRIDES LUMBERING
  NIGHTMARE FORECAST DUMPLINGS BLOWTORCH CLAMBERS STUDYING MISTAKEN
  ABSENT ACTING BLUISH CHOSEN DEBRIS FOSSIL HELIUM LATENCY MYSTIC NEPHEW OBTAIN PASTRY QUIVER
  ALMONDS CAPSIZE DEFROST EARTHLY FRIGHTS GLIMPSE IMPORTS JACKPOT LOCKSMITH
  SPOKE SPOKED WRONG WRONGED SPONGE SPONGED YOKED POLKA ZONED TRIED SPIED WOLFED PLIED TONED
  ADEPTLY AMNESTY CHINTZY CHIMPS CHINOS BEFITS ABORT BEGOT ADOPTS FILMS GLORY FORTY
`).map((w) => w.replace(/\?$/, ''));

export const IN_PLACE_WORDS: readonly string[] = [...new Set(IN_PLACE_RAW)].filter((w) => /^[A-Z]+$/.test(w) && new Set(w).size === w.length && w.length >= 5 && w.length <= 9);

/** Everyday words for sentence ("Chinese") coding — short, lower case, no repeats across themes. */
export const SENTENCE_WORDS: readonly string[] = words(`
  gold price rise high market fall sharp bank loan rate cut news good big deal save money fast slow green
  blue sky clear water river flows city lights bright night day sun rises early late bus train stops here
  there team wins match cup final play hard work pays well rain comes soon farmers sow seeds crop grows tall
  fresh fruit sweet mango ripe red apple milk tea hot cold coffee bread eat drink learn read write book page
  new old story simple words speak truth trust earn spend budget plan smart safe home keep calm walk run
`);

/** Two-letter code syllables (consonant + vowel). */
export const CODE_SYLLABLES: readonly string[] = (() => {
  const cons = 'bdfghjklmnprstvwyz'.split('');
  const vows = 'aeiou'.split('');
  const out: string[] = [];
  for (const c of cons) for (const v of vows) out.push(c + v);
  return out;
})();
